version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: 'postgres'
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgres/data

volumes:
  db-data:


networks:
  app-tier:
    driver: bridge
